# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server
  client:
    taskfile: ./client/Taskfile.yml
    dir: ./client

tasks:
  proto:
    desc: Regenerate all protobuf and gRPC stubs
    cmds:
      - task server:proto
      - task client:proto

  test:
    desc: Run all tests
    cmds:
      - task server:test
      - task client:test
      
  build:
    desc: Build all components
    cmds:
      - task server:build
      - task client:build
