// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: FileSystemService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// upload file request-response messages
type UploadFileRequestFragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequestFragment) Reset() {
	*x = UploadFileRequestFragment{}
	mi := &file_FileSystemService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequestFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequestFragment) ProtoMessage() {}

func (x *UploadFileRequestFragment) ProtoReflect() protoreflect.Message {
	mi := &file_FileSystemService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequestFragment.ProtoReflect.Descriptor instead.
func (*UploadFileRequestFragment) Descriptor() ([]byte, []int) {
	return file_FileSystemService_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequestFragment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadFileRequestFragment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	mi := &file_FileSystemService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_FileSystemService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_FileSystemService_proto_rawDescGZIP(), []int{1}
}

func (x *SuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// download file request-response messages
type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_FileSystemService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_FileSystemService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_FileSystemService_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadFileResponseFragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponseFragment) Reset() {
	*x = DownloadFileResponseFragment{}
	mi := &file_FileSystemService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponseFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponseFragment) ProtoMessage() {}

func (x *DownloadFileResponseFragment) ProtoReflect() protoreflect.Message {
	mi := &file_FileSystemService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponseFragment.ProtoReflect.Descriptor instead.
func (*DownloadFileResponseFragment) Descriptor() ([]byte, []int) {
	return file_FileSystemService_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadFileResponseFragment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// file info message
type FileInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size             int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	LastModifiedTime string                 `protobuf:"bytes,3,opt,name=last_modified_time,json=lastModifiedTime,proto3" json:"last_modified_time,omitempty"`
	IsDirectory      bool                   `protobuf:"varint,4,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_FileSystemService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_FileSystemService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_FileSystemService_proto_rawDescGZIP(), []int{4}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetLastModifiedTime() string {
	if x != nil {
		return x.LastModifiedTime
	}
	return ""
}

func (x *FileInfo) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

type FileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoRequest) Reset() {
	*x = FileInfoRequest{}
	mi := &file_FileSystemService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoRequest) ProtoMessage() {}

func (x *FileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_FileSystemService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoRequest.ProtoReflect.Descriptor instead.
func (*FileInfoRequest) Descriptor() ([]byte, []int) {
	return file_FileSystemService_proto_rawDescGZIP(), []int{5}
}

func (x *FileInfoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_FileSystemService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_FileSystemService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_FileSystemService_proto_rawDescGZIP(), []int{6}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_FileSystemService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_FileSystemService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_FileSystemService_proto_rawDescGZIP(), []int{7}
}

func (x *PongResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_FileSystemService_proto protoreflect.FileDescriptor

const file_FileSystemService_proto_rawDesc = "" +
	"\n" +
	"\x17FileSystemService.proto\x12\x02pb\"C\n" +
	"\x19UploadFileRequestFragment\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"+\n" +
	"\x0fSuccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x13DownloadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"2\n" +
	"\x1cDownloadFileResponseFragment\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x83\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12,\n" +
	"\x12last_modified_time\x18\x03 \x01(\tR\x10lastModifiedTime\x12!\n" +
	"\fis_directory\x18\x04 \x01(\bR\visDirectory\"%\n" +
	"\x0fFileInfoRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fPongResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xaf\x03\n" +
	"\n" +
	"FileSystem\x12D\n" +
	"\n" +
	"UploadFile\x12\x1d.pb.UploadFileRequestFragment\x1a\x13.pb.SuccessResponse\"\x00(\x01\x12M\n" +
	"\fDownloadFile\x12\x17.pb.DownloadFileRequest\x1a .pb.DownloadFileResponseFragment\"\x000\x01\x128\n" +
	"\n" +
	"DeleteFile\x12\x13.pb.FileInfoRequest\x1a\x13.pb.SuccessResponse\"\x00\x122\n" +
	"\vGetFileInfo\x12\x13.pb.FileInfoRequest\x1a\f.pb.FileInfo\"\x00\x122\n" +
	"\tListFiles\x12\x13.pb.FileInfoRequest\x1a\f.pb.FileInfo\"\x000\x01\x12=\n" +
	"\x0fCreateDirectory\x12\x13.pb.FileInfoRequest\x1a\x13.pb.SuccessResponse\"\x00\x12+\n" +
	"\x04Ping\x12\x0f.pb.PingRequest\x1a\x10.pb.PongResponse\"\x00B\x0eZ\fserver/pb;pbb\x06proto3"

var (
	file_FileSystemService_proto_rawDescOnce sync.Once
	file_FileSystemService_proto_rawDescData []byte
)

func file_FileSystemService_proto_rawDescGZIP() []byte {
	file_FileSystemService_proto_rawDescOnce.Do(func() {
		file_FileSystemService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_FileSystemService_proto_rawDesc), len(file_FileSystemService_proto_rawDesc)))
	})
	return file_FileSystemService_proto_rawDescData
}

var file_FileSystemService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_FileSystemService_proto_goTypes = []any{
	(*UploadFileRequestFragment)(nil),    // 0: pb.UploadFileRequestFragment
	(*SuccessResponse)(nil),              // 1: pb.SuccessResponse
	(*DownloadFileRequest)(nil),          // 2: pb.DownloadFileRequest
	(*DownloadFileResponseFragment)(nil), // 3: pb.DownloadFileResponseFragment
	(*FileInfo)(nil),                     // 4: pb.FileInfo
	(*FileInfoRequest)(nil),              // 5: pb.FileInfoRequest
	(*PingRequest)(nil),                  // 6: pb.PingRequest
	(*PongResponse)(nil),                 // 7: pb.PongResponse
}
var file_FileSystemService_proto_depIdxs = []int32{
	0, // 0: pb.FileSystem.UploadFile:input_type -> pb.UploadFileRequestFragment
	2, // 1: pb.FileSystem.DownloadFile:input_type -> pb.DownloadFileRequest
	5, // 2: pb.FileSystem.DeleteFile:input_type -> pb.FileInfoRequest
	5, // 3: pb.FileSystem.GetFileInfo:input_type -> pb.FileInfoRequest
	5, // 4: pb.FileSystem.ListFiles:input_type -> pb.FileInfoRequest
	5, // 5: pb.FileSystem.CreateDirectory:input_type -> pb.FileInfoRequest
	6, // 6: pb.FileSystem.Ping:input_type -> pb.PingRequest
	1, // 7: pb.FileSystem.UploadFile:output_type -> pb.SuccessResponse
	3, // 8: pb.FileSystem.DownloadFile:output_type -> pb.DownloadFileResponseFragment
	1, // 9: pb.FileSystem.DeleteFile:output_type -> pb.SuccessResponse
	4, // 10: pb.FileSystem.GetFileInfo:output_type -> pb.FileInfo
	4, // 11: pb.FileSystem.ListFiles:output_type -> pb.FileInfo
	1, // 12: pb.FileSystem.CreateDirectory:output_type -> pb.SuccessResponse
	7, // 13: pb.FileSystem.Ping:output_type -> pb.PongResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_FileSystemService_proto_init() }
func file_FileSystemService_proto_init() {
	if File_FileSystemService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_FileSystemService_proto_rawDesc), len(file_FileSystemService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_FileSystemService_proto_goTypes,
		DependencyIndexes: file_FileSystemService_proto_depIdxs,
		MessageInfos:      file_FileSystemService_proto_msgTypes,
	}.Build()
	File_FileSystemService_proto = out.File
	file_FileSystemService_proto_goTypes = nil
	file_FileSystemService_proto_depIdxs = nil
}
