# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  admin:
    taskfile: ./admin/Taskfile.yml
    dir: ./admin

tasks:
  default:
    desc: Show available server tasks
    cmds:
      - task --list
    silent: true

  run:
    desc: Run the file server
    cmds:
      - GRPC_PORT=8080 && go run .
    deps:
      - build

  test:
    desc: Test the file server
    cmds:
      - go test -v ./...
    deps:
      - build

  build:
    desc: Build the server binary
    cmds:
      - go build ./...
    deps:
      - admin:ui:build
      - tidy
      - proto

  tidy:
    desc: Sync Go module dependencies
    cmds:
      - go mod tidy
    deps:
      - proto

  proto:
    desc: Regenerate Go protobuf and gRPC stubs
    cmds:
      - mkdir -p pb
      - protoc -I ../proto --go_out=pb --go-grpc_out=pb --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative ../proto/*.proto
    silent: true
