[package]
name = "insane-sdfs-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["full"] }
libp2p = { workspace = true, features = [ "tokio", "gossipsub", "mdns", "tcp", "macros", "noise", "yamux", "quic", "request-response" ] }
futures = { workspace = true }
async-trait = "0.1.89"
serde = "1.0.228"
cbor = "0.4.1"
